import type { ComponentToken } from './types'

export const COMPONENT_TOKENS: Record<string, ComponentToken> = {
  client: {
    nodeId: 'client',
    baseLatencyMs: 0,
    baseRpsCapacity: Infinity,
    scaleFactor: 1.0,
    failureMode: 'Client-side failure — users cannot connect',
    tradeoffs: ['Generates load', 'No server-side capacity to tune'],
    capacityNote: 'Client is the traffic source. Capacity is determined by downstream services.',
    realWorldExample: 'Mobile app, browser, or API consumer. At scale: billions of clients (WhatsApp, iOS).',
  },
  load_balancer: {
    nodeId: 'load_balancer',
    baseLatencyMs: 1,
    baseRpsCapacity: 500000,
    scaleFactor: 1.0,
    failureMode: 'All traffic drops — single point of failure if not HA-configured',
    tradeoffs: [
      'Distributes load evenly across servers',
      'Adds 1-2ms overhead per request',
      'Must be HA-configured (active-passive) to avoid being SPOF itself',
    ],
    capacityNote: 'AWS ALB: ~500k RPS per load balancer. HAProxy: ~200k RPS on 4-core VM. Auto-scales in cloud.',
    realWorldExample: 'AWS ALB routes 1M+ RPS for Netflix. Cloudflare Load Balancer handles global anycast routing.',
  },
  api_server: {
    nodeId: 'api_server',
    baseLatencyMs: 10,
    baseRpsCapacity: 10000,
    scaleFactor: 1.0,
    failureMode: 'Service unavailable — all API calls fail with 503',
    tradeoffs: [
      'Stateless = horizontally scalable',
      'CPU-bound for compute, I/O-bound for data fetching',
      'Memory leak or goroutine leak can cause slow degradation',
    ],
    capacityNote: 'Node.js: ~10k RPS single core, ~80k RPS on 8-core. Go: ~100k RPS single binary. Depends heavily on handler complexity.',
    realWorldExample: 'Stripe API servers: stateless Go services, ~100k RPS per pod. Deploy more pods behind LB to scale.',
  },
  server: {
    nodeId: 'server',
    baseLatencyMs: 10,
    baseRpsCapacity: 8000,
    scaleFactor: 1.0,
    failureMode: 'Service unavailable',
    tradeoffs: [
      'General-purpose compute',
      'May be stateful — harder to scale horizontally',
      'Session affinity required if stateful',
    ],
    capacityNote: 'Typical web server: 5-10k RPS. Horizontally scalable with stateless design.',
    realWorldExample: 'Django/Rails monolith. Instagram ran Django until 1M users, then moved to microservices.',
  },
  database: {
    nodeId: 'database',
    baseLatencyMs: 5,
    baseRpsCapacity: 5000,
    scaleFactor: 0.7,
    failureMode: 'Full outage — no reads or writes possible. Data may be at risk.',
    tradeoffs: [
      'ACID guarantees — strong consistency',
      'Single node = SPOF without replication',
      'Vertical scaling hits ceiling at ~10k RPS; horizontal sharding is complex',
    ],
    capacityNote: 'Postgres single node: ~5k RPS read, ~2k RPS write. With 3 read replicas: ~15k read RPS. RDS r6g.4xlarge: ~20k RPS.',
    realWorldExample: 'PostgreSQL powers Shopify, GitHub, Instagram (early). At scale, Shopify shards by merchant_id across 2000+ pods.',
  },
  read_replica: {
    nodeId: 'read_replica',
    baseLatencyMs: 5,
    baseRpsCapacity: 5000,
    scaleFactor: 1.0,
    failureMode: 'Read traffic falls back to primary — may overwhelm it',
    tradeoffs: [
      'Multiplies read capacity linearly',
      'Replication lag: typically 10-100ms — reads may be stale',
      'Adds operational complexity (failover promotion)',
    ],
    capacityNote: 'Each replica adds ~5k RPS read capacity. 5 replicas = 25k RPS reads. Replication lag: Aurora <10ms, MySQL ~50ms.',
    realWorldExample: 'GitHub uses 1 primary + 5 read replicas per cluster. Twitter: 1 primary + 4 replicas, geo-distributed.',
  },
  cache: {
    nodeId: 'cache',
    baseLatencyMs: 0.5,
    baseRpsCapacity: 100000,
    scaleFactor: 1.0,
    failureMode: 'Cache miss storm — all traffic falls through to database, likely causing overload',
    tradeoffs: [
      'Sub-millisecond reads — 10-100x faster than DB',
      'Data can be stale (TTL-based or invalidation bugs)',
      'Memory-bound — data that exceeds RAM gets evicted',
    ],
    capacityNote: 'Redis single node: ~100k ops/sec, <1ms p99. 6-node cluster: ~600k ops/sec. Memcached: ~1M ops/sec per node (simpler ops).',
    realWorldExample: 'Twitter: L1 Twemcache (in-process) + L2 Redis. 99.5% cache hit rate for timeline reads. Bitly: L1 Memcached + L2 Redis.',
  },
  cdn: {
    nodeId: 'cdn',
    baseLatencyMs: 5,
    baseRpsCapacity: 1000000,
    scaleFactor: 1.0,
    failureMode: 'Cache miss — origin servers receive full traffic load',
    tradeoffs: [
      '95%+ cache hit rate eliminates origin load for static assets',
      'Dynamic content cannot be cached — origin still needed',
      'Cache invalidation is slow (TTL-based, or purge API)',
    ],
    capacityNote: 'Cloudfront: 248+ Tbps aggregate, 600+ PoPs globally. 95% hit rate = 20x capacity multiplier on origin. <10ms TTFB from PoP.',
    realWorldExample: 'Netflix: 100% of video served via CDN (Open Connect). 15% of global internet traffic. GitHub: CDN for static assets, ~1ms load time globally.',
  },
  api_gateway: {
    nodeId: 'api_gateway',
    baseLatencyMs: 2,
    baseRpsCapacity: 200000,
    scaleFactor: 1.0,
    failureMode: 'All API requests blocked — gateway is a chokepoint',
    tradeoffs: [
      'Centralized auth, rate limiting, routing',
      'Adds 2-5ms latency per request',
      'Single configuration point — misconfiguration affects all services',
    ],
    capacityNote: 'AWS API Gateway: 10k RPS default (soft limit), 500k RPS max. Kong: ~100k RPS on 4-core. Adds ~2ms overhead.',
    realWorldExample: 'Airbnb: Kong API Gateway handles auth and routing for 30+ microservices. AWS API Gateway powers millions of serverless APIs.',
  },
  rate_limiter: {
    nodeId: 'rate_limiter',
    baseLatencyMs: 1,
    baseRpsCapacity: 300000,
    scaleFactor: 1.0,
    failureMode: 'All requests pass through unthrottled — DoS/abuse vulnerability exposed',
    tradeoffs: [
      'Protects backend from traffic spikes and abuse',
      'Token bucket in Redis: ~100k checks/sec per Redis node',
      'Distributed rate limiting requires coordination — adds latency',
    ],
    capacityNote: 'Token bucket in Redis: 1 Redis INCR per request, ~100k RPS per Redis node. Sliding window: 2x Redis ops. Leaky bucket: fixed queue depth.',
    realWorldExample: 'Stripe: rate limits at API key level (100 req/s by default). GitHub: 5k req/hour authenticated. Twitter: per-endpoint limits.',
  },
  message_queue: {
    nodeId: 'message_queue',
    baseLatencyMs: 20,
    baseRpsCapacity: 50000,
    scaleFactor: 1.0,
    failureMode: 'Message delivery stops — workers starve, producers may block',
    tradeoffs: [
      'Decouples producers from consumers — async processing',
      'Messages survive consumer crashes (durable queues)',
      'At-least-once delivery: consumers must be idempotent',
    ],
    capacityNote: 'RabbitMQ: ~50k msg/sec per node. Kafka: 1M+ msg/sec per broker. SQS: 300 TPS (standard) or 3k TPS (FIFO). Latency: 5-50ms.',
    realWorldExample: 'LinkedIn uses Kafka for 7 trillion messages/day. Shopify: RabbitMQ for order processing. Airbnb: SQS for async payments.',
  },
  stream: {
    nodeId: 'stream',
    baseLatencyMs: 10,
    baseRpsCapacity: 1000000,
    scaleFactor: 1.0,
    failureMode: 'Event stream halts — real-time consumers lose data',
    tradeoffs: [
      'High throughput, low latency event streaming',
      'Replay capability — consumers can rewind',
      'Partition key design critical for even distribution',
    ],
    capacityNote: 'Kafka: 1M+ events/sec per broker, 10ms p99 latency. Kinesis: 1k records/sec per shard. Partition = unit of parallelism.',
    realWorldExample: 'Netflix: Kafka processes 1 trillion events/day for recommendations. Uber: Kafka for 1M+ events/sec real-time surge pricing.',
  },
  worker: {
    nodeId: 'worker',
    baseLatencyMs: 100,
    baseRpsCapacity: 1000,
    scaleFactor: 1.0,
    failureMode: 'Queue depth grows unbounded — message backlog accumulates',
    tradeoffs: [
      'Async processing — user not blocked waiting for slow operations',
      'Harder to debug failures (no synchronous error return)',
      'Scaling workers scales throughput linearly',
    ],
    capacityNote: 'Worker throughput = (1000ms / job_duration_ms) × parallelism. 100ms jobs: 10/sec per worker. 10ms jobs: 100/sec per worker.',
    realWorldExample: 'Shopify: workers for order confirmation emails, inventory updates. GitHub: Sidekiq workers for CI/CD job queuing.',
  },
  function: {
    nodeId: 'function',
    baseLatencyMs: 50,
    baseRpsCapacity: 100000,
    scaleFactor: 1.0,
    failureMode: 'Function invocations fail — cold starts or concurrency limits',
    tradeoffs: [
      'Zero operational overhead — no servers to manage',
      'Cold start: 100ms-2s for first invocation',
      'Concurrency limits: AWS Lambda default 1k concurrent, hard limit 10k',
    ],
    capacityNote: 'AWS Lambda: 1M invocations/month free, $0.20 per million after. Cold start: <100ms (Node/Python), 1-2s (Java). 15min max execution.',
    realWorldExample: 'Airbnb: Lambda for image resizing (1M+/day). Netflix: Lambda for media encoding triggers. Coca-Cola: vending machine APIs on Lambda.',
  },
  container: {
    nodeId: 'container',
    baseLatencyMs: 10,
    baseRpsCapacity: 10000,
    scaleFactor: 1.0,
    failureMode: 'Container crash — Kubernetes restarts it within 10-30s (brief downtime)',
    tradeoffs: [
      'Isolated, reproducible environment',
      'Kubernetes orchestration: auto-scaling, self-healing',
      'Container startup: 1-5s (faster than VMs, slower than processes)',
    ],
    capacityNote: 'Kubernetes HPA: scale from 2 → 20 pods in ~60s. Each pod: 10k RPS. 20 pods: 200k RPS. Startup: 5s after image pull.',
    realWorldExample: 'Spotify: 1800+ microservices on Kubernetes. Google runs 2B+ containers/week. Monzo: 1500 container pods for UK banking.',
  },
  blob_storage: {
    nodeId: 'blob_storage',
    baseLatencyMs: 30,
    baseRpsCapacity: 100000,
    scaleFactor: 1.0,
    failureMode: 'File uploads/downloads fail — users cannot access stored assets',
    tradeoffs: [
      'Virtually unlimited storage at low cost (~$0.023/GB/month S3)',
      'Not a database — no queries, no transactions',
      '30-100ms latency for small files; large files can take seconds',
    ],
    capacityNote: 'S3: 3,500 PUT/COPY/POST/DELETE + 5,500 GET/HEAD per second per prefix. Use multiple prefixes for >5.5k RPS. Virtually unlimited storage.',
    realWorldExample: 'S3 stores 300 trillion objects. Dropbox moved FROM S3 to their own system at $75M/year savings. Netflix stores 1 PB+ on S3.',
  },
  search: {
    nodeId: 'search',
    baseLatencyMs: 20,
    baseRpsCapacity: 5000,
    scaleFactor: 0.9,
    failureMode: 'Search unavailable — fallback to DB query (much slower)',
    tradeoffs: [
      'Full-text search, fuzzy matching, faceted filters — not possible in standard DBs',
      'Near-real-time indexing: 1-10s lag from write to searchable',
      'Resource-intensive: CPU for indexing, RAM for segment caches',
    ],
    capacityNote: 'Elasticsearch: ~5k queries/sec per node, 20ms p99. Index latency: 1-5s. 3-node cluster handles ~15k queries/sec with replication.',
    realWorldExample: 'GitHub search: Elasticsearch across 8B+ files. Wikipedia: Elasticsearch for full-text search. Airbnb: 150M listings indexed for search.',
  },
  monitoring: {
    nodeId: 'monitoring',
    baseLatencyMs: 0,
    baseRpsCapacity: Infinity,
    scaleFactor: 1.0,
    failureMode: 'Blind operations — failures go undetected until users complain',
    tradeoffs: [
      'Essential for production operations — without it, mean time to detect is hours',
      'Observability tax: ~5% CPU overhead for metrics collection',
      'Alert fatigue if thresholds set too aggressively',
    ],
    capacityNote: 'Prometheus: scrapes 1M+ metrics/sec. Datadog: $15/host/month. Alerting pipeline: 30s-5min MTTD (mean time to detect) depending on scrape interval.',
    realWorldExample: 'Netflix: 2B+ metrics/min through Atlas. Cloudflare: Grafana + Prometheus monitoring 1T+ requests/month. PagerDuty: 12M+ alerts/month.',
  },
}
