const EDGE_LABEL: Record<string, string> = {
  'client→load_balancer': 'HTTPS',
  'client→cdn': 'HTTPS',
  'client→api_gateway': 'HTTPS',
  'client→api_server': 'HTTPS',
  'client→rate_limiter': 'HTTPS',
  'load_balancer→api_server': 'HTTP',
  'load_balancer→server': 'HTTP',
  'load_balancer→function': 'HTTP',
  'cdn→blob_storage': 'Origin Pull',
  'cdn→api_server': 'HTTP',
  'cdn→load_balancer': 'HTTP',
  'cdn→rate_limiter': 'HTTP',
  'api_gateway→api_server': 'HTTP',
  'api_gateway→rate_limiter': 'Check',
  'api_gateway→load_balancer': 'HTTP',
  'rate_limiter→load_balancer': 'HTTP',
  'rate_limiter→api_server': 'HTTP',
  'api_server→cache': 'Redis',
  'api_server→database': 'SQL',
  'api_server→read_replica': 'SQL',
  'api_server→blob_storage': 'S3 API',
  'api_server→message_queue': 'Publish',
  'api_server→stream': 'Produce',
  'api_server→search': 'Query',
  'api_server→worker': 'RPC',
  'api_server→function': 'Invoke',
  'api_server→monitoring': 'Metrics',
  'server→cache': 'Redis',
  'server→database': 'SQL',
  'server→read_replica': 'SQL',
  'server→message_queue': 'Publish',
  'server→monitoring': 'Metrics',
  'message_queue→worker': 'Consume',
  'message_queue→function': 'Trigger',
  'stream→worker': 'Consume',
  'stream→function': 'Trigger',
  'worker→database': 'SQL',
  'worker→blob_storage': 'S3 API',
  'worker→cache': 'Redis',
  'worker→monitoring': 'Metrics',
  'function→database': 'SQL',
  'function→blob_storage': 'S3 API',
  'database→read_replica': 'Replicate',
  'monitoring→api_server': 'Scrape',
  'monitoring→database': 'Scrape',
  'monitoring→server': 'Scrape',
}

export function getEdgeLabel(sourceNodeId: string, targetNodeId: string): string {
  return EDGE_LABEL[`${sourceNodeId}→${targetNodeId}`] ?? ''
}
